apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: default
data:
  DB_USER: postgres
  DB_PASS: IIT-sem3-2025
  DB_HOST: database-1.c9u682e2kvbi.ap-southeast-1.rds.amazonaws.com
  DB_PORT: "5432"
